theme: jekyll-theme-midnight
page_title: Devblog | Robo Instructus | Alex Butler Games
title: Alex Butler's Games
description: Updates on Robo Instructus development, game design and programming
google_analytics: UA-100809402-1

defaults:
- scope:
    path: "" # all
  values:
    layout: default
    author: Alex Butler
    catagories: gamedev

exclude:
- node_modules
- gulpfile.js
- package.json
- README.md
- package-lock.json
- publish-drafts

plugins:
- jekyll-feed
